### ISSUE TITLE
General Polish

### ISSUE THREAD

**Issue by MrSamuelStreamer** [MrSamuelStreamer/GenerationsFlavourPack#30]
_You are a bold one._

- VE Tribals adds an "advance age" gizmo on objects such as campfires which advances the age but it is totally unused and probably just causes confusion. Also requires _all_ tech of a level researched, which is no use in certain scenarios. Could do with being hidden?

- Cornerstone points need to be given on techadvancing level up instead

**Comment by keyz182** [comment]
![unnamed](https://github.com/user-attachments/assets/9c247b3b-35bd-49b7-a6f9-c6a611728b04)
One Polish General, coming right up.

**Comment by keyz182** [comment]
Polish General has disabled "Advance to" gizmo, and cornerstone points have been addressed already.
