### ISSUE TITLE
Removal of Tech Advancing

### ISSUE THREAD

**Issue by MrSamuelStreamer** [MrSamuelStreamer/GenerationsFlavourPack#36]
Re: Discord conversation about falling back on VE Tribals totally manual system.

Issues with mod:
- Window will not close when changing configs, only resolved with a quick load or reboot, [video here (direct download)](https://cdn.discordapp.com/attachments/1306816479374741640/1318558679766925372/2024-12-17_12-41-05.mp4?ex=6762c2f6&is=67617176&hm=ede1185d0d109c8c85859855583be1194c0d84b1caa6b3f148eeefdbd6bb43e7&)
- Configs are not applying correctly when shared via the direct download or when applied via the mod
- Redundant system is already in place with VE tribal where tech advancing is manual and allows much more granular control
- Previous mods that were dependent on tech advancing (including Gen flavour pack) are no longer

Issues with removal:
- Configs will have to be remake to now only accept actual colonist tech level rather than tech advancings 95% threshold system (minor fix)
- Save game has a tracker for tech advancing which will almost certainly error out on preexisting games being loaded (will investigate)
- Need to ensure Gen Flavour Pack tech advances are all tied to VE Tribal (config popup screen)

**Comment by keyz182** [comment]
> Save game has a tracker for tech advancing which will almost certainly error out on preexisting games being loaded (will investigate)

Confirmed ignorable. Will throw an error on loading into save, but doesn't break. Won't appear for following saves.

> Need to ensure Gen Flavour Pack tech advances are all tied to VE Tribal (config popup screen)

Done and pushed to git.
